const sponsor = 
[
    {
        store: "Source IT",
        item: "Apple Computer",
        model: 2025,
        imgUrl: "images/icom.webp",
        promo: "Introducing Eagle's Newest",
        discount: 50
    },
    {
        store: "Barry Electronics",
        item: "Window 11 Computer",
        model: 2025,
        imgUrl: "images/wcom.webp",
        promo: "Ultimate Deals",
        discount: 10
    },
    {
        store: "Italian House",
        item: "Classic Man",
        model: 2025,
        imgUrl: "images/classic-man.webp",
        promo: "Big Sale",
        discount: 40
    },
    {
        store: "Real Kits",
        item: "Jordan",
        model: 2014,
        imgUrl: "images/jordana.webp",
        promo: "Last in stock",
        discount: 45
    }
]

let numOfIteration = 0; 
const arrLength = sponsor.length;
let iterationIndex = [];

// display random item after every 2 mins

async function displayRandomPromo(disObj) 
{

    let index = generateRandomNum(arrLength, iterationIndex);
    const objToDisplay = sponsor[index];

        disObj.innerHTML = 
        `
            <div class="sp-details">
                <p>${objToDisplay.promo}</p>
                <p>${objToDisplay.item}: Get ${objToDisplay.discount}% discount on each purchase</p>
            </div>

            <div class="sp-img-cnt">
                <img src="${objToDisplay.imgUrl}" alt="Image of ${objToDisplay.item} width="300" height = "200"">
            </div>

            <div class="sp-btt-cnt">
                <button type="button" id="promo-shopNow">Shop Now</button>.
            </div>
        `

        setTimeout(() => 
            {
                // Rest number of iteration to have an endless loop

                if(numOfIteration == arrLength)
                {
                    numOfIteration = 0;
                    iterationIndex = []
                }
               
                    displayRandomPromo(disObj);
               
            }, 20000);
    }


function generateRandomNum(range, numsGenerated)
{
    // numsGenerated is an argument passed to generateRandomNum to indexs that have been generated by random number to avoid generating 1 item more that once over a period.

    let randNum = Math.floor(Math.random() * range);
    if((numsGenerated.includes(randNum) & numOfIteration < range))
    {
        randNum = generateRandomNum(range, numsGenerated)
        
    }
    else 
    {
        iterationIndex.push(randNum);
        numOfIteration ++; 
    }

    return randNum;
}

export {displayRandomPromo, generateRandomNum}
